# Generated by Django 4.1.6 on 2023-02-16 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientamount",
            name="amount",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Количество не может быть меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        1000, "Количество не может быть больше 1000"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
